[package]
name = "cavestory_save_editor"
version = "0.1.0"
edition = "2021"
description = "Partially usable. compatible with cavestory(+)"
authors = ["poly000"]
license-file = "LICENSE"

[dependencies]
inquire = "0.2.1"