[package]
name = "cavestory-save-lib"
version = "1.1.1"
edition = "2021"
description = "profile.dat edit lib for cavestory"
authors = ["poly000"]
license-file = "LICENSE"
repository = "https://github.com/poly000/cavestory-save-lib"

[dependencies]

[profile.release]
opt-level = "z"
strip = true
codegen-units = 1
panic = "abort"
