use std::lazy::SyncLazy;

pub static WEAPON: SyncLazy<Vec<&str>> = SyncLazy::new(|| {
    vec![
        "None",
        "Snake",
        "Polar Star",
        "Fireball",
        "Machine Gun",
        "Missile Launcher",
        "Missiles [Bad]",
        "Bubbler",
        "Unknown [Bad]",
        "Blade",
        "Super Missile",
        "Super Missiles [Bad]",
        "Nemesis",
        "Spur",
        "\"Hajime\" [Bad]",
    ]
});

pub static INVENTORY: SyncLazy<Vec<&str>> = SyncLazy::new(|| {
    vec![
        "None",
        "Arthur's Key",
        "Map System",
        "Santa's Key",
        "Silver Locket",
        "Beast Fang",
        "Life Capsule",
        "ID Card",
        "Jellyfish Juice",
        "Rusted Key",
        "Gum Key",
        "Gum Base",
        "Charcoal",
        "Bomb",
        "Dog",
        "Life Pot",
        "Cure-All",
        "Clinic Key",
        "Booster v0.8",
        "Arms Barrier",
        "Turbocharge",
        "Air Tank",
        "290 Counter",
        "Booster v2.0",
        "Mimiga Mask",
        "Teleporter Room Key",
        "Sue's Letter",
        "Controller",
        "Broken Sprinkler",
        "Sprinkler",
        "Tow Rope",
        "Medal of the Red Ogre",
        "Mister Little",
        "Mushroom Badge",
        "Ma Pignon",
        "Curly's Panties",
        "Alien Medal",
        "Chako's Rouge",
        "Whimsical Star",
        "Iron Bond",
    ]
});
